### ISSUE TITLE
Path not set in the app

### ISSUE THREAD

**Issue by mike-live** [JGeek00/my-server-status-app#1]
#### Description

The android App version 1.3.0 requests URL on the server without provided path.

Current request URL looks like:
`/v1/check-credentials`

Expected request URL:
`/mypath/v1/check-credentials`

#### Solution

The path should be set in the serverObj on Line 320 of `/lib/widgets/add_server_modal.dart`.
In the invocation of Server constructor should be also line like:
`path: pathControler.text`

**Comment by JGeek00** [comment]
Will push an update fixing it.

**Comment by JGeek00** [comment]
Fixed on v1.3.1.
