### ISSUE TITLE
Do you have a multilingual plan?

### ISSUE THREAD

**Issue by wlc743859910** [JGeek00/my-server-status-app#4]
Hope to support the Chinese language

**Comment by JGeek00** [comment]
Hi. I only speak spanish and english, so I cannot add other languages, but if you want to add support for chinese, feel free to add the translations and submit a pull request.

To add a new translation follow this steps:
1. Create a new file inside ``lib/l10n``. On this case, for chinese it would be called ``lib/l10n/app_cn.arb``
2. On ``main.dart``, on line 170, add a new entry with the 'cn' value
3. Run ``flutter pub get`` to generate the translations.
